name = "Taxonomy"
uuid = "fea09e6a-dc4a-42ec-a35f-5cfade855812"
authors = ["Aaron Peikert", "Maximilian S. Ernst", "Clifford Bode", "Nicklas Hafiz"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "1"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
